kind: Service
apiVersion: v1
metadata:
  name:  gcd-service-server
spec:
  selector:
    app:  gcd-server
  # type:  NodePort
  ports:
  - port:  7000
    targetPort:  7001
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gcd-server-deployment
  labels:
    app: gcd-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gcd-server
  template:
    metadata:
      labels:
        app: gcd-server
    spec:
      containers:
      - name: gcd-server-pod
        image: gcd-server-image
        imagePullPolicy: Never
        ports:
         - containerPort: 7001